return {
	{ "erikbackman/brightburn.vim" },
	{ "folke/tokyonight.nvim" },
	{ "catppuccin/nvim",                 name = "catppuccin" },
	{ "sainnhe/gruvbox-material" },
	{ "EdenEast/nightfox.nvim" },
	{ "rose-pine/neovim",                name = "rose-pine" },
	{ "navarasu/onedark.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "joshdick/onedark.vim" },
	{ "morhetz/gruvbox" },
	{ "arcticicestudio/nord-vim" },
	{ "Mofiqul/vscode.nvim" },
	{ "dracula/vim" },
	{ "NLKNguyen/papercolor-theme" },
	{ "altercation/vim-colors-solarized" },
	{ "sainnhe/everforest" },
	{ "nanotech/jellybeans.vim" },
	{ "jacoborus/tender.vim" },
	{ "dracula/vim" },
	{ "NTBBloodbath/doom-one.nvim" },
	{ "AlphaTechnolog/pywal.nvim" },
}
